apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: bzy8v3ces-nodejs
  janus-idp.io/tekton: bzy8v3ces-nodejs
  backstage.io/kubernetes-id: bzy8v3ces-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bzy8v3ces-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
