apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: bzy8v3ces-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bzy8v3ces-nodejs 
  name: bzy8v3ces-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: bzy8v3ces-nodejs 
